# there's no bash ¯\_(ツ)_/¯
language: python
services: docker
env:
- distro=debian
- distro=ubuntu
- distro=archlinux
  
before_install:
  - import os; os.system("docker build test/Dockerfile.${distro}")

script: true
