language: c
services: docker
os: osx
env:
- distro=debian
- distro=ubuntu
- distro=archlinux

script:
  - >
    set -ex;
    git config --global user.name "githooker";
    git config --global user.email "githooker@boddenberg.it";
    docker build -f "$PWD/tests/Dockerfile.$distro" .
