language: c
services: docker
os: 
  - osx
  - linux
script:
  - >
    set -ex;
    git config --global user.name "githooker";
    git config --global user.email "githooker@boddenberg.it";
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker build -f "$PWD/tests/Dockerfile.ubuntu" .;
      docker build -f "$PWD/tests/Dockerfile.debian" .;
      docker build -f "$PWD/tests/Dockerfile.archlinux" .;
    else
      ./test/run_tests.sh;
    fi
