# there's no bash ¯\_(ツ)_/¯
language: python
services: docker

jobs:
  include:
    - os: osx
    - os: linux
      env:
        - distro=debian
        - distro=ubuntu
        - distro=archlinux

script: ls
